~ position creation logic fix
TakeprofitTechnology/GapLocker pull request #19
Opened 2020-08-24 11:44 UTC by YumiHasegawa

https://app.asana.com/0/1163711838222381/1189661327395030

2020-08-24 14:25 UTC, YuriySavlukov requested changes

2020-08-24 14:25 UTC, YuriySavlukov commented on GapLocker/PluginInstance.h
> +                auto& position = std::find_if(calcPositions.begin(), calcPositions.end(), [&login](const WIMTPosition& obj) {return obj->Login() == login; });
Тут явно просится сделать calcPositions мапой по логину.

2020-08-24 14:25 UTC, YuriySavlukov commented on GapLocker/PluginInstance.h
> +                else //netting volume
Я не уверен, что будет правильным неттить buy и sell лок позиции, так как у них разные цены. Нужно тогда или неттить с учётом цены, или группировать по направлению, или вообще ничего не неттить и оставить, как было.

2020-08-24 16:12 UTC, YuriySavlukov requested changes

2020-08-24 16:12 UTC, YuriySavlukov commented on GapLocker/PluginInstance.h
> +            order->VolumeInitial(position->VolumeExt());
Тут нужно VolumeInitialExt()

2020-08-24 16:12 UTC, YuriySavlukov commented on GapLocker/PluginInstance.h
> +            deal->VolumeExt(order->VolumeInitial());
И тут Ext

2020-08-24 17:26 UTC, YuriySavlukov approved these changes

2020-08-25 07:58 UTC, Jukerony approved these changes

2020-08-25 07:59 UTC, merged